/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthcheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthcheck endpoint to verify API is running
         * @description A simple endpoint to verify that the API is running and responsive.
         */
        get: operations["health_check_healthcheck_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provide an email and password to create a new user account.
         * @description Upon successful registration, access and refresh tokens are issued.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provide an email and password to gain access with an existing account.
         * @description Upon successful login, access and refresh tokens are issued.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Obtain new access and refresh tokens using a valid refresh token.
         * @description Refresh tokens are long-lived and can be used to get new access tokens without re-authenticating. Previous refresh tokens are invalidated upon use.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/idioms/search/{search_phrase}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return all idioms that sufficiently match the provided phrase
         * @description The search phrase can be a partial or complete match to an idiom.
         */
        get: operations["get_idiom_idioms_search__search_phrase__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/idioms/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return a random idiom from the collection
         * @description This is a fun way to learn a new figure of speech that you may not have known.
         */
        get: operations["get_random_idiom_idioms_random_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/idioms/by-letter/{starting_letter}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return all idioms that begin with a requested letter
         * @description Results will be returned in ascending alphabetical order.
         */
        get: operations["get_idioms_starting_with_letter_idioms_by_letter__starting_letter__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/idioms/by-synonym/{synonym}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return all idioms that are synonyms with the requested word or phrase
         * @description This can help discover a colorful figure of speech for a literal word or phrase.
         */
        get: operations["get_idioms_for_synonym_idioms_by_synonym__synonym__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiServiceTier
         * @description Defines the different API access tiers available to users.
         *     This provides a way to categorize users based on their subscription level.
         *     Certain endpoints may have access restrictions based on these tiers.
         * @enum {string}
         */
        ApiServiceTier: "free" | "premium" | "admin";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Idiom
         * @description An Idiom represents a figure of speech along with its definition.
         */
        Idiom: {
            /**
             * Idiom
             * @description a figure of speech
             * @example skating on thin ice
             */
            idiom: string;
            /**
             * Definition
             * @description definition for the idiom or literal equivalent meaning
             * @example to proceed with risky behavior
             */
            definition: string;
            /**
             * Synonyms
             * @description synonyms for the figure of speech
             * @example risk-taking
             * @example in danger
             */
            synonyms: string[];
            /**
             * Example
             * @description using the idiom in a sentence, showing an example of properly using it
             * @default Example usage not available.
             * @example Jason was skating on thin ice after the teacher caught him cheating on the test.
             */
            example: string;
        };
        /**
         * LoginRequest
         * @description Schema for user login requests.
         *     Contains a user's email and password fields required for authentication.
         */
        LoginRequest: {
            /**
             * Username
             * Format: email
             * @description a user email address associated with the account
             * @example john.doe@example.com
             */
            username: string;
            /**
             * Password
             * @description a user's secret password
             * @example 12345678
             */
            password: string;
        };
        /**
         * RegisterRequest
         * @description Schema for user registration and login requests.
         *     Contains a user's email and password fields required for authentication.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             * @description a user email address associated with the account
             * @example john.doe@example.com
             */
            email: string;
            /**
             * Password
             * @description a user's secret password
             * @example 12345678
             */
            password: string;
            /**
             * @description the API access tier for the user account
             * @default free
             * @example free
             * @example premium
             * @example admin
             */
            service_tier: components["schemas"]["ApiServiceTier"];
        };
        /**
         * TokenResponse
         * @description Schema for responses containing access and refresh tokens.
         */
        TokenResponse: {
            /**
             * Access Token
             * @description access token
             */
            access_token: string;
            /**
             * Refresh Token
             * @description refresh token
             */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_healthcheck_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Database service not available */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User account is disabled */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query: {
                refresh_token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid refresh token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found or disabled */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh token expired, please log in again */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_idiom_idioms_search__search_phrase__get: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description partial or complete idiom to retrieve */
                search_phrase: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Idiom"][];
                };
            };
            /** @description Idiom not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_random_idiom_idioms_random_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Idiom"];
                };
            };
            /** @description No idioms available */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_idioms_starting_with_letter_idioms_by_letter__starting_letter__get: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Single Latin character */
                starting_letter: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Idiom"][];
                };
            };
            /** @description Idiom not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_idioms_for_synonym_idioms_by_synonym__synonym__get: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description word or phrase that means the same thing as potential idioms */
                synonym: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Idiom"][];
                };
            };
            /** @description Idiom not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
